### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by pinghe** [winery/BPMN4TOSCA2BPEL#1]
src\main\java\de\ustutt\iaas\bpmn2bpel\model\param\TopologyParameter.java:5:  com.sun.xml.internal.ws.util does not exist

java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

see http://www.oracle.com/technetwork/java/faq-sun-packages-142232.html

**Comment by fetzerms** [comment]
I created a pull request which should fix the error. You may also simply (manually) remove the com.sun.xml import as it is currently unused.
